language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: TpZDns/S7LARoMPOstzDmA3f26/3h0f3eRv4oOoOTL31jfNy5N+2FEHypiAqUMFUI/SpA0j7BS4TpT6JX0NY+gMq1AUxKB4bg9glrqU/4KskniDnX+sbJoQnv+xD4D7D0VEX/+eLs/Z9kcsIMWrbqibKf4XQ1EQ0eTIukXMCT22D7YD45qqCsWMHKZYhan7u/36ZcDaECdMQplAsW+mtssNk2vzye3vJVYqZJTKOlcf18z0ZReY1eRGbRGjXHLBqAcZ+jfppLnNncAFb3BiofzIfhT28EW3Zyg1klPLYWtGVssf9LlsCoz3E/cdEvGkNaBCHlwN7LJod3j7Wq4Mvsta2K7gK1tQE2chHGeXiHJOxJi404Ivh5T3tXe43fNQDEAIknYwAuD1Afwc2mPlcLlN/HVmP7/Nte7HCzWcowxowSn5uOPcqi7t2QAUTlSlXD1Rr4Np9/Os2M5JmSyGIeAETRl6hq8og1P5YOolUJL9qaym6MNnsqXQ//3a2fPWs0961LC/wt7pVQdot1w55oA2gwMsV7OjsN6mHmgHICNfUzgvoaoldd1knMY6OrW4mzFG1NlSAd+lE47UVRVK3iAnwO0SGI1ZLlnhRCuKf1pytyCuJ3HQETt/cPQlkCJ3m+rlI2igjbxalWWn9rnSnAdbJ0oxpEVIUzeObdAkfeYk=
  # REGISTRY_TOKEN slug=mgen editor=cozy space=default
  - secure: M0xtVoQZzBNt25Rqi7U8gmKjmIywe1RV1PFWL7INZLeqL+9qVC/3M3Wol7ACESV4dGUuwdV9MvO6ajPBB1pe2UffTjwZFVMRIVT0BJt5yh5g+1GFEeUIwPhUuBL9vq4uJ9M3ZNCe5d3OkhyEyrJJijR1R6jDasoDgRaEwBvrOBu4XlsIwatSaxgAvf77ha29mesURfbNaN32S1syZJb1sgB7kEp2YgV2pI+zrLeL9/+cUtx76ScSFf3qBlsu87bkw0/hTusESGr+VZf2gvJyqw+cG3SiXsm9xcJu6uuRi5xRPWLP75581W4uZap+zCsT5nMteeVDXPZC2Dff+0sXlQED1mYacncuWGR/xXMjDXYmAlQbn7WODq9dEbYVpMdvXaKtMUQ6QOypX5QX2l4Krr1pQD3jEHvsjPs3XX1LtGWz5GmZejLHsKCBg/0/AdMkCNcOVrkH7tpj48n8uL9wpLwWY/3CBDnZoVbpIOhBIURz73z2Sfhr68QYssXtc+F5fH70qMJZlGHLXv1nDHDcv3iUNBZPxP9LhYVwgxWh+otZBr2hKVDnuHSZlm4sbkwQaGrKYQQ1NqyZj/d/1raUExiUL+m0WdurjQssFYlxaqU5UzZ0dScn7DfOmUgXmXm8xfWquNtQNTzo8Dc8sJjBx/6RDYZI2d/mS255IVLE/U8=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
